<html>
    <head>
        <title>Registration</title>
    
<link rel="stylesheet" type="text/css" href="CSS.css" >
    </head>
    <body>
        <div id="header">
            <h1>City Gallery</h1>
        </div>
         <div id="menu">
            <ul>
                <li><a href="/">Home</a></li>
                <li><a href="/reg.php">Registration</a></li>
            </ul>
        </div>
        <div id="nav">
            London<br>
            Paris<br>
            Tokyo
        </div>
        
    
       